---
title: "3PT Defense Profiles"
output: html_notebook
---

```{r}
acc_opp_data <- read.csv("ACC Opponent Totals 25-26 - Sheet1.csv")
```

```{r}
acc_opp_data <- acc_opp_data |>
  mutate(
    logo = case_when(
      Team == "Duke" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/duke_logo.webp",
      Team == "North Carolina" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/unc_logo.webp",
      Team == "Virginia" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/uva_logo.webp",
      Team == "Notre Dame" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/nd_logo.webp",
      Team == "Virginia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/vt_logo.webp",
      Team == "Stanford" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/stanford_logo.webp",
      Team == "SMU" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/smu_logo.webp",
      Team == "Boston College" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/bc_logo.webp",
      Team == "Clemson" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/clemson_logo.webp",
      Team == "Pittsburgh" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/pitt_logo.webp",
      Team == "Syracuse" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/syr_logo.webp",
      Team == "Miami (FL)" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/miami_logo.webp",
      Team == "Georgia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/gt_logo.webp",
      Team == "NC State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/ncstate_logo.webp",
      Team == "Florida State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/fsu_logo.webp",
      Team == "Louisville" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/louisville_logo.webp",
      Team == "Wake Forest" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/wake_logo.webp",
      Team == "California" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/cal_logo.webp",
    )
  )
```

```{r}
avg_3PA <- mean(acc_opp_data$X3PA)
avg_3P_perc <- mean(acc_opp_data$X3P.)
```

```{r}
ggplot(acc_opp_data, aes(x = X3P.*100, y = X3PA))+
  geom_image(aes(image = logo), size = 0.05) +
  geom_hline(yintercept = avg_3PA, linetype = "dashed") +
  geom_vline(xintercept = avg_3P_perc*100, linetype = "dashed") +
  labs(
    x = "Oppenent Three Point % Made",
    y = "Opponent Three Point Attempts",
    title = "ACC Three-Point Defense Profile (2025-26)",
    caption = "Data: Stathead Basketball"
  )
```
```{r}
acc_opp_data <- acc_opp_data |>
  mutate(
    z_score_3PA = (X3PA - mean(X3PA)) / sd(X3PA),
    z_score_3P_pct = (X3P. - mean(X3P.)) / sd(X3P.)
  )

acc_opp_data <- acc_opp_data |>
  mutate(
    sig_3PA = abs(z_score_3PA) > 1.96,
    sig_3P_pct = abs(z_score_3P_pct) > 1.96
  )

acc_opp_data |>
  filter(sig_3PA | sig_3P_pct) |>
  select(Team, X3PA, z_score_3PA, X3P., z_score_3P_pct)
```

