---
title: "NCAA #1 Seeds (2005-2025)"
output: html_notebook
---

```{r}
one_seeds <- read_csv("NCAA_1_seeds.csv")
```
```{r}
head(one_seeds)
```

```{r}
str(one_seeds)
```
```{r}
one_seeds <- one_seeds |>
  mutate(tourney_year = as.numeric(paste0("20", substr(Season, 6, 7))))
```

```{r}
one_seeds_by_season <- one_seeds |>
  group_by(tourney_year) |>
  summarise(
    avg_FG_per = mean(FG_perc),
    avg_3P_perc = mean(x3P_perc),
    avg_FT_perc = mean(FT_perc),
    avg_ORB = mean(ORB),
    avg_DRB = mean(DRB),
    avg_TOV = mean(TOV),
    avg_PTS = mean(PTS)
  )
```

```{r}
one_seeds_by_season_perc <- one_seeds_by_season |>
  pivot_longer(
    cols = c(avg_FG_per, avg_3P_perc, avg_FT_perc),
    names_to = "stat",
    values_to = "value"
  )
```

```{r}
one_seeds_by_season_ORB_DRB_TOV <- one_seeds_by_season |>
  pivot_longer(
    cols = c(avg_ORB, avg_DRB, avg_TOV),
    names_to = "stat",
    values_to = "value"
  )
```

```{r}
one_seeds_by_season_PTS <- one_seeds_by_season |>
  pivot_longer(
    cols = avg_PTS,
    names_to = "stat",
    values_to = "value"
  )
```

```{r}
# plotting average percentage of three-pointers, field goals, and free throws made per game by 1 seeds

one_seeds_by_season_perc |>
  ggplot(aes(x = tourney_year, value, color = stat)) +
  geom_line()
```
```{r}
# plotting average number of offensive rebounds, defensive rebounds, and turnovers made per game by 1 seeds

one_seeds_by_season_ORB_DRB_TOV |>
  ggplot(aes(x = tourney_year, value, color = stat)) +
  geom_line()
```
```{r}
# plotting average number of points scored per game by 1 seeds

one_seeds_by_season_PTS |>
  ggplot(aes(x = tourney_year, value, color = stat)) +
  geom_line()
```
```{r}
unique(one_seeds$Team)
```

```{r}
one_seeds <- one_seeds |>
  mutate(
    logo = case_when(
      Team == "Duke" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/duke_logo.webp",
      Team == "Houston" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/houston_logo.webp",
      Team == "Alabama" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/alabama_logo.webp",
      Team == "Auburn" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/auburn_logo.webp",
      Team == "Florida" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/florida_logo.webp",
      Team == "Connecticut" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/uconn_logo.webp",
      Team == "Purdue" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/purdue_logo.webp",
      Team == "North Carolina" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/unc_logo.webp",
      Team == "Kansas" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/kansas_logo.webp",
      Team == "Arizona" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/arizona_logo.webp",
      Team == "Baylor" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/baylor_logo.webp",
      Team == "Gonzaga" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/gonzaga_logo.webp",
      Team == "Illinois" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/illinois_logo.webp",
      Team == "Michigan" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/michigan_logo.webp",
      Team == "Virginia" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/uva_logo.webp",
      Team == "Villanova" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/villanova_logo.webp",
      Team == "Xavier" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/xavier_logo.webp",
      Team == "Oregon" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/oregon_logo.webp",
      Team == "Kentucky" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/kentucky_logo.webp",
      Team == "Wisconsin" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/wisconsin_logo.webp",
      Team == "Wichita State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/wichitast_logo.webp",
      Team == "Indiana" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/indiana_logo.webp",
      Team == "Michigan State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/michiganst_logo.webp",
      Team == "Ohio State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/ohiost_logo.webp",
      Team == "Memphis" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/memphis_logo.webp",
      Team == "UCLA" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/ucla_logo.webp",
      Team == "Washington" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/washington_logo.webp",
      Team == "Pittsburgh" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/pitt_logo.webp",
      Team == "Syracuse" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/syr_logo.webp",
      Team == "Louisville" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/louisville_logo.webp",
    )
  )
```

```{r}
# Free throw percentage of #1 seeds who made the Final Four vs those who did not

one_seeds |>
  ggplot(aes(x = tourney_year, y = FT_perc)) +
  geom_point(
    data = subset(one_seeds, Champion == "Yes"),
    color = "gold",
    size = 6,
    alpha = 0.8
  ) +
  geom_image(aes(image = logo), size = 0.05) +
  facet_wrap(~Final_Four) +
  labs(
    x = "Tournament Year",
    y = "Free Throw %",
    title = "Average Free Throw % of #1 Seeds",
    subtitle = "Conference Play"
  ) +
  theme_minimal()
  
```
```{r}
# Three-pointer percentage of #1 seeds who made the Final Four vs those who did not

one_seeds |>
  ggplot(aes(x = tourney_year, y = x3P_perc)) +
    geom_point(
    data = subset(one_seeds, Champion == "Yes"),
    color = "gold",
    size = 6,
    alpha = 0.8
  ) +
  geom_image(aes(image = logo), size = 0.05) +
  facet_wrap(~Final_Four) +
  labs(
    x = "Tournament Year",
    y = "Three Point %",
    title = "Average Three Point % of #1 Seeds",
    subtitle = "Conference Play"
  ) +
  theme_minimal()
```
```{r}
# Points per game of #1 seeds who made the Final Four vs those who did not

one_seeds |>
  ggplot(aes(x = tourney_year, y = PTS)) +
    geom_point(
    data = subset(one_seeds, Champion == "Yes"),
    color = "gold",
    size = 6,
    alpha = 0.8
  ) +
  geom_image(aes(image = logo), size = 0.05) +
  facet_wrap(~Final_Four) +
  labs(
    x = "Tournament Year",
    y = "Points per Game",
    title = "Average Points per Game of #1 Seeds",
    subtitle = "Conference Play"
  ) +
  theme_minimal()
```
```{r}
# TOV per game of #1 seeds who made the Final Four vs those who did not

one_seeds |>
  ggplot(aes(x = tourney_year, y = TOV)) +
    geom_point(
    data = subset(one_seeds, Champion == "Yes"),
    color = "gold",
    size = 6,
    alpha = 0.8
  ) +
  geom_image(aes(image = logo), size = 0.05) +
  facet_wrap(~Final_Four) +
  labs(
    x = "Tournament Year",
    y = "Turnovers",
    title = "Average Turnovers per Game of #1 Seeds",
    subtitle = "Conference Play"
  ) +
  theme_minimal()
```

```{r}
t.test(TOV ~ Champion, data = one_seeds)
t.test(PTS ~ Champion, data = one_seeds)
t.test(FT_perc ~ Champion, data = one_seeds)
t.test(x3P_perc ~ Champion, data = one_seeds)
```
```{r}
t.test(TOV ~ Final_Four, data = one_seeds)
t.test(PTS ~ Final_Four, data = one_seeds)
t.test(FT_perc ~ Final_Four, data = one_seeds)
t.test(x3P_perc ~ Final_Four, data = one_seeds)
```


